# Giving netherite to all players
replaceitem entity @a slot.weapon.mainhand 1 netherite_sword
replaceitem entity @a slot.weapon.offhand 1 shield
replaceitem entity @a slot.armor.chest 1 netherite_chestplate
replaceitem entity @a slot.armor.legs 1 netherite_leggings
replaceitem entity @a slot.armor.feet 1 netherite_boots
replaceitem entity @a slot.armor.head 1 netherite_helmet
replaceitem entity @a slot.hotbar 1 netherite_sword
replaceitem entity @a slot.weapon.mainhand 1 netherite_sword
replaceitem entity @a slot.hotbar 2 netherite_pickaxe
replaceitem entity @a slot.hotbar 3 netherite_shovel
replaceitem entity @a slot.hotbar 4 netherite_axe
replaceitem entity @a slot.hotbar 5 netherite_hoe